### ISSUE TITLE
lua5.2 bindings

### ISSUE THREAD

**Issue by fedya** [lxc/lxc#174]
make[3]: Entering directory '/home/fedya/lxc/BUILD/lxc-1.0.0/src/lua-lxc'
x86_64-mandriva-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../../src    -fPIC -DPIC -I../../src  -DVERSION=\"1.0.0\" -DLXCPATH=\"/var/lib/lxc\" -O2  -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -Wall -Werror -c -o core_so-core.o `test -f 'core.c' || echo './'`core.c
x86_64-mandriva-linux-gnu-gcc -fPIC -DPIC -I../../src  -DVERSION=\"1.0.0\" -DLXCPATH=\"/var/lib/lxc\" -O2  -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -Wall -Werror -shared -L../../src/lxc -Wl,-soname,core.so.1 -Wl,--no-undefined  -o core.so core_so-core.o -llxc -lutil -lpthread -lcap 
core_so-core.o:core.c:function lxc_version_get: error: undefined reference to 'lua_pushstring'
core_so-core.o:core.c:function container_get_config_path: error: undefined reference to 'luaL_checkudata'
core_so-core.o:core.c:function container_get_config_path: error: undefined reference to 'lua_pushstring'
core_so-core.o:core.c:function container_state: error: undefined reference to 'luaL_checkudata'
core_so-core.o:core.c:function container_state: error: undefined reference to 'lua_pushstring'
core_so-core.o:core.c:function container_name: error: undefined reference to 'luaL_checkudata'
core_so-core.o:core.c:function container_name: error: undefined reference to 'lua_pushstring'
core_so-core.o:core.c:function container_gc: error: undefined reference to 'luaL_checkudata'
core_so-core.o:core.c:function container_get_keys: error: undefined reference to 'lua_gettop'
core_so-core.o:core.c:function container_get_keys: error: undefined reference to 'luaL_checklstring'
core_so-core.o:core.c:function container_get_keys: error: undefined reference to 'lua_pushnil'
core_so-core.o:core.c:function container_get_config_item: error: undefined reference to 'luaL_checklstring'
core_so-core.o:core.c:function container_get_config_item: error: undefined reference to 'lua_pushnil'
core_so-core.o:core.c:function container_get_cgroup_item: error: undefined reference to 'luaL_checklstring'
core_so-core.o:core.c:function container_get_cgroup_item: error: undefined reference to 'lua_pushnil'
core_so-core.o:core.c:function container_clear_config_item: error: undefined reference to 'luaL_checklstring'
core_so-core.o:core.c:function container_clear_config_item: error: undefined reference to 'lua_pushboolean'
core_so-core.o:core.c:function container_set_config_item: error: undefined reference to 'lua_pushboolean'
core_so-core.o:core.c:function container_set_config_path: error: undefined reference to 'lua_pushboolean'
core_so-core.o:core.c:function container_set_cgroup_item: error: undefined reference to 'lua_pushboolean'
core_so-core.o:core.c:function container_save_config: error: undefined reference to 'lua_gettop'
core_so-core.o:core.c:function container_load_config: error: undefined reference to 'lua_gettop'
core_so-core.o:core.c:function container_wait: error: undefined reference to 'luaL_checkinteger'
core_so-core.o:core.c:function container_shutdown: error: undefined reference to 'luaL_checkinteger'
core_so-core.o:core.c:function container_start: error: undefined reference to 'lua_gettop'
core_so-core.o:core.c:function container_init_pid: error: undefined reference to 'lua_pushinteger'
core_so-core.o:core.c:function lxc_util_usleep: error: undefined reference to 'luaL_checkunsigned'
core_so-core.o:core.c:function container_new: error: undefined reference to 'lua_newuserdata'
core_so-core.o:core.c:function container_new: error: undefined reference to 'lua_getfield'
core_so-core.o:core.c:function container_new: error: undefined reference to 'lua_setmetatable'
core_so-core.o:core.c:function container_new: error: undefined reference to 'lua_pushnil'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_createtable'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'luaL_setfuncs'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_newuserdata'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_createtable'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_pushvalue'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_pushlstring'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_pushcclosure'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_rawset'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_setmetatable'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_rawset'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'luaL_newmetatable'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'luaL_setfuncs'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_pushvalue'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_pushcclosure'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_settable'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_setfield'
core_so-core.o:core.c:function luaopen_lxc_core: error: undefined reference to 'lua_settop'
collect2: error: ld returned 1 exit status

Full log
http://pastebin.com/aCyzweHY

**Comment by LynxChaus** [comment]
Something wrong with lua development package installation.
Current version correctly builds with 5.2 & 5.3 lua version.

**Comment by brauner** [comment]
Newer `lua` bindings seem to be working fine.
