### PR TITLE
Fix regressions in dir_mount

### PR DESCRIPTION
**Pull request by r10r**
Hi @brauner,

I noticed that lxc master doesn't compile when building the image for lxcri.
The relevant changes were introduced in 423374e95314ceac9a6d5e1ddaaa1c438de85056
It seems to me that by accident mount options were used in place of the propagation flags.
This pull request should fix both.

```
rage/dir.c  -fPIC -DPIC -o storage/.libs/liblxc_la-dir.o
In file included from storage/dir.c:11:
storage/dir.c: In function 'dir_mount':
./log.h:358:2: error: '%s' directive argument is null [-Werror=format-overflow=]
  358 |  LXC_DEBUG(&locinfo, format, ##__VA_ARGS__);   \
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
storage/dir.c:185:5: note: in expansion of macro 'DEBUG'
  185 |     DEBUG("Remounted \"%s\" on \"%s\" read-only with options \"%s\", mount flags \"%lu\", and propagation flags \"%lu\"",
      |     ^~~~~
storage/dir.c:185:64: note: format string is defined here
  185 |     DEBUG("Remounted \"%s\" on \"%s\" read-only with options \"%s\", mount flags \"%lu\", and propagation flags \"%lu\"",
      |                                                                ^~
In file included from storage/dir.c:11:
./log.h:353:2: error: '%s' directive argument is null [-Werror=format-overflow=]
  353 |  LXC_TRACE(&locinfo, format, ##__VA_ARGS__);   \
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
storage/dir.c:189:3: note: in expansion of macro 'TRACE'
  189 |   TRACE("Mounted \"%s\" on \"%s\" with options \"%s\", mount flags \"%lu\", and propagation flags \"%lu\"",
      |   ^~~~~
storage/dir.c:189:50: note: format string is defined here
  189 |   TRACE("Mounted \"%s\" on \"%s\" with options \"%s\", mount flags \"%lu\", and propagation flags \"%lu\"",
      |                                                  ^~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:4755: storage/liblxc_la-dir.lo] Error 1
make[2]: Leaving directory '/tmp/lxcri-build/lxc/src/lxc'
make[1]: Leaving directory '/tmp/lxcri-build/lxc/src'
make[1]: *** [Makefile:434: install-recursive] Error 1
make: *** [Makefile:531: install-recursive] Error 1
```

### CODE REVIEW

**Comment by r10r** [comment]
Hmm seems you already working on this -  so it may be obsolete when #3812 is merged.

**Comment by brauner** [comment]
> Hmm seems you already working on this - so it may be obsolete when #3812 is merged.

Yes, that's caused by working on idmapped mount support sorry for the noise. Somehow neither test-suite nor local compiler test caught it.

**Comment by r10r** [comment]
I'm using the  **ubuntu:latest**  docker image to build lxc and lxcri. The build chain from it caught the error. 

I'm not aware of the test-suite details - but maybe the **ubuntu:latest** container would be an option here.
The Dockerfile from lxcri aims to setup a full kubernetes stack but it would be fairly easy to build lxc only. 

see  https://github.com/lxc/lxcri/blob/main/Dockerfile 
and https://github.com/lxc/lxcri/blob/main/install.sh

What about adding a Dockerfile to lxc ?  
I can send a pull request for that.
