### ISSUE TITLE
Can't build with gcc 7.1

### ISSUE THREAD

**Issue by ss1h2a3tw** [lxc/lxc#1603]
# Required information

 * Distribution: Archlinux

# Issue description

Building with gcc 7.1 result in 
`cgroups/cgfsng.c: In function ‘cgfsng_create’:                                                                                                                           cgroups/cgfsng.c:1381:23: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=] 
 snprintf(offset, 5, "-%d", idx);                                                                                                                                                                                                                                                   cgroups/cgfsng.c:1381:3: note: ‘snprintf’ output between 3 and 6 bytes into a destination of size 5`

Adding -Wno-format-truncation to compile flags seems working
But not sure about whether it is a false alarm.

**Comment by brauner** [comment]
That looks like a false alarm to me:

```
	if (idx == 1000) {
		ERROR("Too many conflicting cgroup names");
		goto out_free;
	}
	if (idx)
		snprintf(offset, 5, "-%d", idx);

```

The maximum number reached can be `999` which is `strlen("-") + strlen("999") = 4` which leaves room for the terminating `\0` byte.

**Comment by ss1h2a3tw** [comment]
It seems to be gcc's bug, it give a wrong prediction on idx's range to 0~1000
if we change to `if (idx == 999)` , it will not give the warning
so maybe change to 999 will be a temporary fix?

**Comment by ss1h2a3tw** [comment]
It's confirmed as gcc's bug.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80924
Closing this issue
