### ISSUE TITLE
Build broken with glibc-2.36 and io_uring support

### ISSUE THREAD

**Issue by ganto** [lxc/lxc#4182]
# Required information

 * Distribution: Fedora
 * Distribution version: 37

# Issue description

Even after all the recent fixes from #4179 and #4181 the lxc build still fails against glibc-2.36 if io_uring support is enabled:
```
[16/1615] gcc -Isrc/lxc/liblxc_static.a.p -Isrc/lxc -I../src/lxc -I. -I.. -Isrc -I../src -Isrc/include -I../src/include -I../src/lxc/cgroups -I../src/lxc/storage -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -O0 -Wno-format-signedness -Wno-missing-field-initialize
rs -Wno-unused-parameter -Wvla -Wimplicit-fallthrough=5 -Wcast-align -Wstrict-prototypes -fno-strict-aliasing -fstack-clash-protection --param=ssp-buffer-size=4 -Werror=implicit-function-declaration -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Winit-self -Wunused-but-set-variable -Wno-unused-parameter 
-Wfloat-equal -Wsuggest-attribute=noreturn -Werror=return-type -Werror=incompatible-pointer-types -Wformat=2 -Wshadow -Wendif-labels -Werror=overflow -fdiagnostics-show-option -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -fasynchronous-unwind-tables -fexceptions -Warray-bounds -W
restrict -Wreturn-local-addr -Wstringop-overflow -include config.h -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/re
dhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -pthread -fvisibility=default -MD -MQ src/lxc/liblxc_static.a.p/cgroups_cgfsng.c.o -MF src/lxc/liblxc_static.a.p/cgroups_cgfsng.c.o.d -o src/lxc/liblxc_static.a.p/cgroups_cgfsng.c.o -c ../src/lxc/cg
roups/cgfsng.c                                                                                                                                                 
FAILED: src/lxc/liblxc_static.a.p/cgroups_cgfsng.c.o 
gcc -Isrc/lxc/liblxc_static.a.p -Isrc/lxc -I../src/lxc -I. -I.. -Isrc -I../src -Isrc/include -I../src/include -I../src/lxc/cgroups -I../src/lxc/storage -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -O0 -Wno-format-signedness -Wno-missing-field-initializers -Wno-un
used-parameter -Wvla -Wimplicit-fallthrough=5 -Wcast-align -Wstrict-prototypes -fno-strict-aliasing -fstack-clash-protection --param=ssp-buffer-size=4 -Werror=implicit-function-declaration -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Winit-self -Wunused-but-set-variable -Wno-unused-parameter -Wfloat-eq
ual -Wsuggest-attribute=noreturn -Werror=return-type -Werror=incompatible-pointer-types -Wformat=2 -Wshadow -Wendif-labels -Werror=overflow -fdiagnostics-show-option -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -fasynchronous-unwind-tables -fexceptions -Warray-bounds -Wrestrict -
Wreturn-local-addr -Wstringop-overflow -include config.h -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redha
t-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -pthread -fvisibility=default -MD -MQ src/lxc/liblxc_static.a.p/cgroups_cgfsng.c.o -MF src/lxc/liblxc_static.a.p/cgroups_cgfsng.c.o.d -o src/lxc/liblxc_static.a.p/cgroups_cgfsng.c.o -c ../src/lxc/cgroups/cgfs
ng.c                                                          
In file included from /usr/include/linux/fs.h:19,                                                                                                              
                 from /usr/include/liburing/io_uring.h:11,                                                                                                     
                 from /usr/include/liburing.h:19,
                 from ../src/lxc/macro.h:26,                                                                                                                   
                 from ../src/lxc/af_unix.h:14,                                                                                                                 
                 from ../src/lxc/cgroups/cgroup.h:14,            
                 from ../src/lxc/cgroups/cgfsng.c:34:                                                                                                          
/usr/include/linux/mount.h:95:6: error: redeclaration of ‘enum fsconfig_command’                  
   95 | enum fsconfig_command {                                          
      |      ^~~~~~~~~~~~~~~~
In file included from ../src/lxc/macro.h:18:                                                                                                                   
/usr/include/sys/mount.h:189:6: note: originally defined here
  189 | enum fsconfig_command
      |      ^~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:96:9: error: redeclaration of enumerator ‘FSCONFIG_SET_FLAG’
   96 |         FSCONFIG_SET_FLAG       = 0,    /* Set parameter, supplying no value */
      |         ^~~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:191:3: note: previous definition of ‘FSCONFIG_SET_FLAG’ with type ‘enum fsconfig_command’
  191 |   FSCONFIG_SET_FLAG       = 0,    /* Set parameter, supplying no value */
      |   ^~~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:97:9: error: redeclaration of enumerator ‘FSCONFIG_SET_STRING’
   97 |         FSCONFIG_SET_STRING     = 1,    /* Set parameter, supplying a string value */
      |         ^~~~~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:193:3: note: previous definition of ‘FSCONFIG_SET_STRING’ with type ‘enum fsconfig_command’
  193 |   FSCONFIG_SET_STRING     = 1,    /* Set parameter, supplying a string value */
      |   ^~~~~~~~~~~~~~~~~~~
[...]
```

# Steps to reproduce

 1. Use a Linux distribution with glibc-2.36 (e.g. the upcoming Fedora 37)
 2. Ensure to have the lxc source code with the glibc-2.36 fixes so far (e.g. b3defe05b)
 3. Run `meson setup build` with `-Dio-uring-event-loop=true`
 4. Build will fail

**Comment by juippis** [comment]
This one is probably fixed by glibc upstream now. (no clue when a .1 release is coming though)

**Comment by juippis** [comment]
#4179 this seemed to fix it for me when using the latest glibc-2.36 patch set. It works with `+io-uring` and seems to work with glibc-2.35 too.

**Comment by kloczek** [comment]
Looking on https://github.com/lxc/lxc/compare/lxc-5.0.3...main I thing that it would be goof to release new version.
Possible to do that soon? 🤔

**Comment by stgraber** [comment]
LXC 6.0 will be released in the next few weeks
