### ISSUE TITLE
lxc-3.0.2 fails to build on CentOS 7 with "error: 'for' loop initial declarations are only allowed in C99 mode"

### ISSUE THREAD

**Issue by ganto** [lxc/lxc#2615]
# Required information

 * Distribution: CentOS
 * Distribution version: 7

# Issue description

Building `lxc-3.0.2` on CentOS 7 (`gcc-4.8.5-28.el7_5.1.x86_64`) fails with:
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../src -fPIC -DPIC -DLXCROOTFSMOUNT=\"/usr/lib64/lxc/rootfs\" -DLXCPATH=\"/var/lib/lxc\" -DLXC_GLOBAL_CONF=\"/etc/lxc/lxc.conf\" -DLXCINITDIR=\"/usr/libexec\" -DLIBEXECDIR=\"/usr/libexec\" -DLXCTEMPLATEDIR=\"/usr/share/lxc/templates\" -DLXCTEMPLATECONFIG=\"/usr/share/lxc/config\" -DLOGPATH=\"/var/log/lxc\" -DLXC_DEFAULT_CONFIG=\"/etc/lxc/default.conf\" -DLXC_USERNIC_DB=\"/run/lxc/nics\" -DLXC_USERNIC_CONF=\"/etc/lxc/lxc-usernet\" -DDEFAULT_CGROUP_PATTERN=\"lxc/%n\" -DRUNTIME_PATH=\"/run\" -DSBINDIR=\"/usr/sbin\" -I ../../src -I ../../src/lxc -I ../../src/lxc/storage -I ../../src/lxc/cgroups -DHAVE_SECCOMP -DHAVE_SELINUX -pthread -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -c confile.c  -fPIC -DPIC -o .libs/liblxc_la-confile.o
BUILDSTDERR: In file included from ./utils.h:48:0,
BUILDSTDERR:                  from lsm/lsm.h:31,
BUILDSTDERR:                  from conf.c:100:
BUILDSTDERR: conf.c: In function 'parse_mntopts':
BUILDSTDERR: ./macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 mode
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: conf.c:1909:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(p, s, ",")
BUILDSTDERR:   ^
BUILDSTDERR: ./macro.h:135:2: note: use option -std=c99 or -std=gnu99 to compile your code
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: conf.c:1909:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(p, s, ",")
BUILDSTDERR:   ^
BUILDSTDERR: conf.c: In function 'parse_propagationopts':
BUILDSTDERR: ./macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 mode
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: conf.c:1953:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(p, s, ",")
BUILDSTDERR:   ^
BUILDSTDERR: In file included from utils.h:48:0,
BUILDSTDERR:                  from confile.c:56:
BUILDSTDERR: confile.c: In function 'set_config_group':
BUILDSTDERR: macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 mode
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: confile.c:996:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(token, groups, " \t") {
BUILDSTDERR:   ^
BUILDSTDERR: macro.h:135:2: note: use option -std=c99 or -std=gnu99 to compile your code
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: confile.c:996:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(token, groups, " \t") {
BUILDSTDERR:   ^
BUILDSTDERR: confile.c: In function 'set_config_mount_auto':
BUILDSTDERR: macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 mode
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: confile.c:1637:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(token, autos, " \t") {
BUILDSTDERR:   ^
BUILDSTDERR: confile.c: In function 'set_config_cap_keep':
BUILDSTDERR: macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 mode
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: confile.c:1702:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(token, keepcaps, " \t") {
BUILDSTDERR:   ^
BUILDSTDERR: confile.c: In function 'set_config_cap_drop':
BUILDSTDERR: macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 mode
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: confile.c:1744:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(token, dropcaps, " \t") {
BUILDSTDERR:   ^
BUILDSTDERR: confile.c: In function 'set_config_namespace_clone':
BUILDSTDERR: macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 mode
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: confile.c:2101:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(token, ns, " \t") {
BUILDSTDERR:   ^
BUILDSTDERR: confile.c: In function 'set_config_namespace_keep':
BUILDSTDERR: macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 mode
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: confile.c:2136:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(token, ns, " \t") {
BUILDSTDERR:   ^
BUILDSTDERR: make[3]: *** [liblxc_la-conf.lo] Error 1
BUILDSTDERR: make[3]: *** Waiting for unfinished jobs....
BUILDSTDERR: confile.c: In function 'lxc_fill_elevated_privileges':
BUILDSTDERR: macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 mode
BUILDSTDERR:   for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p); \
BUILDSTDERR:   ^
BUILDSTDERR: confile.c:2457:2: note: in expansion of macro 'lxc_iterate_parts'
BUILDSTDERR:   lxc_iterate_parts(token, flaglist, "|") {
BUILDSTDERR:   ^
BUILDSTDERR: make[3]: *** [liblxc_la-confile.lo] Error 1
```

I guess the issue was introduced by afceba0ca11e5246c9ee22fb5013ee1648b553cb and c97e6a4be8a9cc19a3d9aab760270f4f63eb97b4.

**Comment by brauner** [comment]
LXC should be built with gnu99 at least. By default it will now add gnu11 to the build flags. gcc 4.8 definitely supports both. :)

**Comment by ganto** [comment]
@brauner Thanks for the feedback. It seems that the issue was not really CentOS 7 but the `--disable-werror` which made the "default" gnu11 flag disappear. However, I see it was just recently fixed in #2592, so I'll take the patch from there.
