### ISSUE TITLE
lxc-checkpoint broken in 2.0.9

### ISSUE THREAD

**Issue by Lukey3332** [lxc/lxc#2107]
Hello Everyone, It seems that checkpointing broke in Version 2.0.9. I noticed it in multiple Distributions and tested it with multiple versions of criu.
 * Distribution: Fedora Server 26/27
 * Version: lxc 2.0.9

# What Broke
Checkpointing of Containers using Bridges is not possible anymore (Networktype none or empty works tough). 

# Steps to reproduce

 1. Install Fedora Server 26/27 Minimal, install Packages lxc and lxc-templates
 2. Create Network Bridge
 3. Create Container, add the following to the conf:
```
lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm
```
4. start the Container, lxc-checkpoint works, but restore fails. Output of criu's restore.log:
```
Warn  (criu/cr-restore.c:1161): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
     1: Warn  (criu/libnetlink.c:54): ERROR -34 reported by netlink
     1: Error (criu/net.c:1475): Can't restore link
Error (criu/mount.c:2980): mnt: Can't remove the directory /tmp/.criu.mntns.ojyALO: No such file or directory
Error (criu/cr-restore.c:2171): Restoring FAILED.

```
# Misc
Downgrading `lxc lxc-libs lxc-templates` (to version 2.0.8) makes it work again.

**Comment by brauner** [comment]
On Thu, Jan 25, 2018 at 01:58:33PM -0800, Lukey3332 wrote:
> Hello Everyone, It seems that checkpointing broke in Version 2.0.9. I noticed it in multiple Distributions and tested it with multiple versions of criu.
>  * Distribution: Fedora Server 26/27
>  * Version: lxc 2.0.9
> 
> # What Broke
> Checkpointing of Containers using Bridges is not possible anymore (Networktype none or empty works tough). 
> 
> # Steps to reproduce
> 
>  1. Install Fedora Server 26/27 Minimal, install Packages lxc and lxc-templates
>  2. Create Network Bridge
>  3. Create Container, add the following to the conf:
> ```
> lxc.console = none
> lxc.tty = 0
> lxc.cgroup.devices.deny = c 5:1 rwm
> ```
> 4. start the Container, lxc-checkpoint works, but restore fails. Output of criu's restore.log:
> ```
> Warn  (criu/cr-restore.c:1161): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
>      1: Warn  (criu/libnetlink.c:54): ERROR -34 reported by netlink

It seems like a classic example where systemd is using a new type of
socket protocol or option that criu doesn't know how to restore or
you're moving to a kernel where the protocol for this netlink feature
has changed. @adrianreber know anything about this?

Christian

**Comment by adrianreber** [comment]
@brauner, but if downgrading lxc to version 2.0.8 helps, then it does not sound like a systemd problem, or does it?

It would be good to see the full dump and restore log-file for a better understanding where exactly CRIU is having trouble, but this actually sounds like a change in lxc from version 2.0.8 to 2.0.9 is changing something in the network bridge setup.

**Comment by brauner** [comment]
Oh, I missed that part when reading it, sorry. @Lukey3332, I suspect it is fixed in the current stable branch actually. There were some problems @adrianreber and I encountered.

**Comment by Lukey3332** [comment]
Yep, works with the latest 2.0.x-git version. When will the next Version be released?
